# Generated by Django 5.0 on 2025-07-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
